<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-28T15:37:51 IST" name="Suite" finished-at="2024-04-28T15:39:01 IST" duration-ms="69286">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidation.LoginErrorValidation()[pri:0, instance:MyProjects.Tests.ErrorValidation@38145825]" name="LoginErrorValidation" class="MyProjects.Tests.ErrorValidation"/>
      </group> <!-- ErrorHandling -->
    </groups>
    <test started-at="2024-04-28T15:37:51 IST" name="SubmitOrderTest" finished-at="2024-04-28T15:38:31 IST" duration-ms="39134">
      <class name="MyProjects.Tests.SubmitPage">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:MyProjects.Tests.SubmitPage@239a307b]" started-at="2024-04-28T15:37:52 IST" name="launchApplication" finished-at="2024-04-28T15:37:59 IST" duration-ms="7516" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:MyProjects.Tests.SubmitPage@239a307b]" started-at="2024-04-28T15:37:59 IST" name="submitOrder" data-provider="getData" finished-at="2024-04-28T15:38:05 IST" duration-ms="5746" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Hemavarenya@244, product=ZARA COAT 3, email=tubatihema@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyProjects.Tests.SubmitPage@239a307b]" started-at="2024-04-28T15:38:05 IST" name="tearDown" finished-at="2024-04-28T15:38:05 IST" duration-ms="286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:MyProjects.Tests.SubmitPage@239a307b]" started-at="2024-04-28T15:38:05 IST" name="launchApplication" finished-at="2024-04-28T15:38:12 IST" duration-ms="6405" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:MyProjects.Tests.SubmitPage@239a307b]" started-at="2024-04-28T15:38:12 IST" name="submitOrder" data-provider="getData" finished-at="2024-04-28T15:38:25 IST" duration-ms="13039" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Iamking@000, product=ADIDAS ORIGINAL, email=anshika@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyProjects.Tests.SubmitPage@239a307b]" started-at="2024-04-28T15:38:25 IST" name="tearDown" finished-at="2024-04-28T15:38:25 IST" duration-ms="250" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:MyProjects.Tests.SubmitPage@239a307b]" started-at="2024-04-28T15:38:25 IST" name="launchApplication" finished-at="2024-04-28T15:38:29 IST" duration-ms="4508" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="OrderHistortTest()[pri:0, instance:MyProjects.Tests.SubmitPage@239a307b]" started-at="2024-04-28T15:38:29 IST" name="OrderHistortTest" finished-at="2024-04-28T15:38:30 IST" depends-on-methods="MyProjects.Tests.SubmitPage.submitOrder" duration-ms="943" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistortTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyProjects.Tests.SubmitPage@239a307b]" started-at="2024-04-28T15:38:30 IST" name="tearDown" finished-at="2024-04-28T15:38:31 IST" duration-ms="217" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- MyProjects.Tests.SubmitPage -->
    </test> <!-- SubmitOrderTest -->
    <test started-at="2024-04-28T15:38:31 IST" name="LoginErrorValidation" finished-at="2024-04-28T15:39:01 IST" duration-ms="29683">
      <class name="MyProjects.Tests.ErrorValidation">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:MyProjects.Tests.ErrorValidation@38145825]" started-at="2024-04-28T15:38:31 IST" name="launchApplication" finished-at="2024-04-28T15:38:36 IST" duration-ms="4801" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:MyProjects.Tests.ErrorValidation@38145825]" started-at="2024-04-28T15:38:36 IST" name="LoginErrorValidation" finished-at="2024-04-28T15:38:36 IST" duration-ms="641" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at MyProjects.Tests.ErrorValidation.LoginErrorValidation(ErrorValidation.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyProjects.Tests.ErrorValidation@38145825]" started-at="2024-04-28T15:38:36 IST" name="tearDown" finished-at="2024-04-28T15:38:37 IST" duration-ms="264" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:MyProjects.Tests.ErrorValidation@38145825]" started-at="2024-04-28T15:38:37 IST" name="launchApplication" finished-at="2024-04-28T15:38:41 IST" duration-ms="4710" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:MyProjects.Tests.ErrorValidation@38145825]" started-at="2024-04-28T15:38:41 IST" name="LoginErrorValidation" finished-at="2024-04-28T15:38:42 IST" duration-ms="597" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email password.]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at MyProjects.Tests.ErrorValidation.LoginErrorValidation(ErrorValidation.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyProjects.Tests.ErrorValidation@38145825]" started-at="2024-04-28T15:38:43 IST" name="tearDown" finished-at="2024-04-28T15:38:43 IST" duration-ms="255" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:MyProjects.Tests.ErrorValidation@38145825]" started-at="2024-04-28T15:38:43 IST" name="launchApplication" finished-at="2024-04-28T15:38:48 IST" duration-ms="5483" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValidation()[pri:0, instance:MyProjects.Tests.ErrorValidation@38145825]" started-at="2024-04-28T15:38:48 IST" name="ProductErrorValidation" finished-at="2024-04-28T15:39:00 IST" duration-ms="12016" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:MyProjects.Tests.ErrorValidation@38145825]" started-at="2024-04-28T15:39:00 IST" name="tearDown" finished-at="2024-04-28T15:39:01 IST" duration-ms="321" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- MyProjects.Tests.ErrorValidation -->
    </test> <!-- LoginErrorValidation -->
  </suite> <!-- Suite -->
</testng-results>
